export const colorTheme = 'theme-dark'
export const C29_COLOR = '#5f6fff'
export const C31_COLOR = '#a25fff'
export const CANCELED_PAYMENT_COLOR = '#C0392B'
export const EXPIRED_PAYMENT_COLOR = '#D4AC0D'
export const POOL_NAME = 'MWCPool'
