name: Deploy to Azure

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.AZURE_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your_server_ip >> ~/.ssh/known_hosts

    - name: Deploy to Azure
      run: |
        ssh svc_mwc@your_server_ip << 'EOF'
        cd /path/to/your/project
        git pull origin main
        ./restart_script.sh
        EOF
